# Generated by Django 4.1.5 on 2023-01-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='Must type something here', max_length=120)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.BooleanField(blank=True)),
                ('checklist', models.BooleanField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Body_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_body', models.TextField(blank=True, null=True)),
                ('title', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_body_desc', to='server.todo')),
            ],
        ),
        migrations.CreateModel(
            name='Body_checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklistBody', to='server.checklist_body')),
                ('title', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_body_checklist', to='server.todo')),
            ],
        ),
    ]
